### ISSUE TITLE
远程连接时报错

### ISSUE THREAD

**Issue by PierXuY** [KenyonY/flaxkv#8]
启动服务：
![image](https://github.com/KenyonY/flaxkv/assets/98803367/5ddd1bef-e561-4185-8770-ee9e1e35416c)

然后执行：
```Python
from flaxkv import dictdb
import numpy as np

db = dictdb('http://localhost:8000', remote=True)
db[1] = 1

print(len(db))
```

报错如下：
![image](https://github.com/KenyonY/flaxkv/assets/98803367/be687e4c-2f3e-48e5-9601-b95b15489e9f)

版本号：
- Name: flaxkv    Version: 0.1.6
- Name: httpx    Version: 0.25.2
- Name: msgpack    Version: 1.0.7

**Comment by KenyonY** [comment]
我在README遗漏了一些重要信息，这是一个远程调用的示例：
```python
db = dictdb("http://localhost:8000",
            remote=True,
            db_name="test_db",
            rebuild=0)
```
其中，db_name是必要的

**Comment by PierXuY** [comment]
可以了
